import {spawn} from 'node:child_process';
import {existsSync,readdirSync,statSync} from 'node:fs';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
function discover(){if(process.env.COMIC_CODEX_CLI)return process.env.COMIC_CODEX_CLI;const root=path.join(process.env.LOCALAPPDATA||path.join(os.homedir(),'AppData','Local'),'OpenAI','Codex','bin');try{const list=readdirSync(root,{withFileTypes:true}).filter(x=>x.isDirectory()).map(x=>path.join(root,x.name,'codex.exe')).filter(existsSync).sort((a,b)=>statSync(b).mtimeMs-statSync(a).mtimeMs);if(list.length)return list[0];}catch{}return path.join(process.env.APPDATA||path.join(os.homedir(),'AppData','Roaming'),'npm/node_modules/@openai/codex/bin/codex.js');}
const cli=discover();
function stop(child){if(!child||child.exitCode!==null)return;if(process.platform==='win32'){const killer=spawn('taskkill',['/pid',String(child.pid),'/T','/F'],{windowsHide:true,stdio:'ignore'});killer.on('error',()=>child.kill());}else child.kill('SIGTERM');}
export function runCli(args,{input='',signal,onEvent,timeout=300000}={}){return new Promise((resolve,reject)=>{if(signal?.aborted)return reject(Error('작업을 취소했습니다.'));const child=spawn(cli.endsWith('.js')?process.execPath:cli,cli.endsWith('.js')?[cli,...args]:args,{windowsHide:true,stdio:['pipe','pipe','pipe']});let stdout='',stderr='',buffer='',settled=false;const done=(error,result)=>{if(settled)return;settled=true;clearTimeout(timer);signal?.removeEventListener('abort',abort);error?reject(error):resolve(result);};const abort=()=>{stop(child);done(Error('작업을 취소했습니다.'));};const timer=setTimeout(()=>{stop(child);done(Error('AI 응답 시간이 초과되었습니다. 원문은 보관되어 있으니 다시 시도해 주세요.'));},timeout);signal?.addEventListener('abort',abort,{once:true});child.on('error',e=>done(Error('Codex 실행 실패: '+e.message)));child.stdout.on('data',chunk=>{stdout+=chunk;buffer+=chunk;if(stdout.length>8e6){stop(child);done(Error('AI 응답 크기가 너무 큽니다.'));return;}const lines=buffer.split('\n');buffer=lines.pop();for(const line of lines){let event;try{event=JSON.parse(line);}catch{continue;}if(['command_execution','mcp_tool_call','web_search','file_change'].includes(event.item?.type)){stop(child);done(Error('이야기 구성 요청에서 불필요한 도구 실행이 감지되어 중단했습니다.'));return;}onEvent?.(event);}});child.stderr.on('data',chunk=>{if(stderr.length<12000)stderr+=chunk;});child.on('close',code=>code===0?done(null,{stdout,stderr}):done(Error(`Codex 요청 실패 (${code}): ${(stderr||stdout).slice(-1600)}`)));child.stdin.on('error',e=>{if(e.code!=='EPIPE')done(e);});child.stdin.end(input);});}
let healthCache,healthAt=0;
export async function codexHealth(){if(healthCache&&Date.now()-healthAt<30000)return healthCache;if(!existsSync(cli))return {available:false,detail:'Codex 실행 파일을 찾을 수 없습니다.'};try{const r=await runCli(['login','status'],{timeout:15000});const available=/Logged in/i.test(r.stdout+r.stderr);healthCache={available,detail:available?'현재 ChatGPT 로그인으로 연결됨':'Codex 로그인 상태를 확인해 주세요.'};}catch(e){healthCache={available:false,detail:e.message};}healthAt=Date.now();return healthCache;}
export async function runCodexJson({schema,prompt,jobDir,model,effort,referenceImages=[],signal,onEvent,attempt=0}){if(!existsSync(cli))throw Error('Codex 실행 파일을 찾을 수 없습니다.');await mkdir(jobDir,{recursive:true});let bytes=0;if(referenceImages.length>6)throw Error('AI 참고 이미지는 한 번에 6개까지입니다.');for(const a of referenceImages){if(!path.isAbsolute(a.file)||!['image/png','image/jpeg','image/webp'].includes(a.mime)||!Number.isSafeInteger(a.bytes)||a.bytes<1)throw Error('참고 이미지가 올바르지 않습니다.');bytes+=a.bytes;}if(bytes>24*1024*1024)throw Error('AI 참고 이미지 합계는 24MB까지입니다.');const schemaFile=path.join(jobDir,'plan-schema.json'),outputFile=path.join(jobDir,`response-${attempt}.json`);await writeFile(schemaFile,JSON.stringify(schema));const args=['exec','--ignore-user-config','--ephemeral','--skip-git-repo-check','--sandbox','read-only','--json','--output-schema',schemaFile,'--output-last-message',outputFile,'-C',jobDir,'-c','features.shell_tool=false','-m',model,'-c',`model_reasoning_effort=${JSON.stringify(effort)}`];if(referenceImages.length)args.push('--image',...referenceImages.map(a=>a.file));args.push('-');let usage={};await runCli(args,{input:prompt,signal,timeout:Number(process.env.COMIC_AI_TIMEOUT_MS)||900000,onEvent:e=>{if(e.type==='turn.completed')usage=e.usage||{};if(e.type==='turn.started')onEvent?.('말의 맥락과 장면의 흐름을 읽고 있습니다.');}});return {raw:await readFile(outputFile,'utf8'),usage};}
