import path from 'node:path';
import {mkdir,readFile,readdir,writeFile} from 'node:fs/promises';
import {identifyImage,MAX_ASSET_BYTES} from './assets.mjs';
import {panelDrawingRequest,SHOTS} from '../shared/contract.mjs';
const clean=value=>String(value??'').replaceAll('\r','');
const list=value=>(value||[]).map(v=>'- '+clean(v)).join('\n')||'- none yet';
export function toMarkdown(project,profile){const i=project.interpretation;return `# ${clean(project.title)}\n\n${project.sourceMode==='fictional'?'This is a fictional example and doesn’t claim real experience.':'Concrete places, props, actions and dialogue not in the source are staging suggestions below.'}\n\n## Original memo\n\n${clean(project.raw)}\n\n## The story as I understood it\n\n${i?clean(i.summary):'The AI plan hasn’t been run yet.'}\n\n${i?`Angle: ${clean(i.angle)}\n\nKey point: ${clean(i.keyPoint)}\n\nVoice: ${clean(i.tone)}\n\n### Opening hook candidates\n\n${i.hooks.map((h,n)=>`${n+1}. ${h.text}${n===project.selectedHook?' [selected]':''}\n   ${h.why}\n   Opening scene: ${h.openingScene||''}`).join('\n')}\n\n### Phrases to keep\n\n${list(i.keepPhrases)}\n\n### Confirmed from the source\n\n${list(i.knownFacts)}\n\n### Interpretation or assumptions\n\n${list(i.assumptions)}\n\n### Read from the references\n\n${list(i.referenceNotes)}\n\n### Worth knowing\n\n${list(i.questions)}\n\n`:''}## Series settings\n\nArt style status: ${clean(profile.style)}\n\nVoice: ${clean(profile.voice)}\n\nContext: ${clean(profile.context)}\n\nFixed characters: ${clean(profile.characterNotes)||'not set yet'}\n\nAvoid: ${clean(profile.avoid)}\n\n${project.panels.map((p,n)=>`## Panel ${n+1} · ${p.title}\n\nRole of this panel: ${p.beat}\n\nShot: ${SHOTS[p.shot]} · ${p.seconds}s\n\nSetting: ${p.setting}\n\nAction: ${p.action}\n\nExpression and gesture: ${p.expression}\n\nComposition and white space: ${p.composition}\n\nNarration: ${p.caption||'(none)'}\n\nDialogue: ${p.dialogue||'(no dialogue)'}\n\nEvidence type: ${{source:'From the source',interpretation:'Context reading',staging:'Staging suggestion'}[p.sourceKind]||'Staging suggestion'}\n\nEvidence and staging: ${p.sourceNote}\n\n### Picture request\n\n${panelDrawingRequest(project,profile,p)}\n\n`).join('')}## References\n\n${[...profile.assets,...project.assets].map(a=>`- ${a.role} · ${a.name}${a.characterName?' · '+a.characterName:''}${a.notes?' · '+a.notes:''}`).join('\n')||'none'}\n`;}
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc32(b){let c=0xffffffff;for(const v of b)c=crcTable[(c^v)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
export function zip(entries){let offset=0;const parts=[],directory=[];for(const {name,data}of entries){const filename=Buffer.from(name),b=Buffer.isBuffer(data)?data:Buffer.from(data),crc=crc32(b);const h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt32LE(crc,14);h.writeUInt32LE(b.length,18);h.writeUInt32LE(b.length,22);h.writeUInt16LE(filename.length,26);const d=Buffer.alloc(46);d.writeUInt32LE(0x02014b50);d.writeUInt16LE(20,4);d.writeUInt16LE(20,6);d.writeUInt16LE(0x800,8);d.writeUInt32LE(crc,16);d.writeUInt32LE(b.length,20);d.writeUInt32LE(b.length,24);d.writeUInt16LE(filename.length,28);d.writeUInt32LE(offset,42);parts.push(h,filename,b);directory.push(d,filename);offset+=h.length+filename.length+b.length;}const center=Buffer.concat(directory),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(center.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...parts,center,end]);}
export async function exportProject({project,profile,readAsset,format='zip'}){if(!['markdown','json','zip'].includes(format))throw Object.assign(Error('Please choose an export format.'),{status:400});const snapshot={...project,jobs:[],revisions:[]};const data={schemaVersion:2,exportedAt:new Date().toISOString(),project:snapshot,profile,notes:'Editable script, picture requests and image assets. Images with generation metadata are AI-generated; the rest were imported by the user.'};if(format==='json')return {data:JSON.stringify(data,null,2),mime:'application/json; charset=utf-8',filename:'comic-story.json'};const markdown=toMarkdown(project,profile);if(format==='markdown')return {data:markdown,mime:'text/markdown; charset=utf-8',filename:'comic-story.md'};const entries=[{name:'story.md',data:markdown},{name:'story.json',data:JSON.stringify(data,null,2)},{name:'series.json',data:JSON.stringify(profile,null,2)}];for(const [n,p]of project.panels.entries())entries.push({name:`drawing-requests/${String(n+1).padStart(2,'0')}.txt`,data:panelDrawingRequest(project,profile,p)});let total=0;const manifest=[];for(const [n,a]of [...profile.assets,...project.assets].entries()){const bytes=await readAsset(a);total+=bytes.length;if(total>200*1024*1024)throw Error('The reference is too large. Split it into separate assets.');const extension={'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[a.mime]||'bin';const filename=`references/${String(n+1).padStart(2,'0')}-${a.role}.${extension}`;entries.push({name:filename,data:bytes});manifest.push({...a,file:filename,url:undefined});}entries.push({name:'references.json',data:JSON.stringify(manifest,null,2)},{name:'READ-ME.txt',data:'Review the flow in story.md and use the per-panel requests in the drawing-requests folder. references.json maps each image to its role and character name. Everything follows the current series’ art style and fixed characters. This package is never published to any external app automatically.'});return {data:zip(entries),mime:'application/zip',filename:'comic-production.zip'};}
// Instagram slides are rendered in the browser; the server only stores them. Each export gets its own folder so nothing is overwritten.
const SLIDE_STAMP=/^\d{8}-\d{6}$/;
export async function saveSlide(store,projectId,{stamp,index,data}={}){
 store.getProject(projectId);
 if(typeof stamp!=='string'||!SLIDE_STAMP.test(stamp)||!Number.isInteger(index)||index<1||index>10||typeof data!=='string')throw Object.assign(Error('The slide save request is invalid.'),{status:400});
 const bytes=Buffer.from(data,'base64');
 if(!bytes.length||bytes.length>MAX_ASSET_BYTES||identifyImage(bytes).mime!=='image/png')throw Object.assign(Error('Slides must be PNG images.'),{status:400});
 const dir=path.join(store.projectDir(projectId),'slides',stamp),file=path.join(dir,String(index).padStart(2,'0')+'.png');
 await mkdir(dir,{recursive:true});await writeFile(file,bytes);
 return {file,dir};
}
export async function slidesZip(store,projectId,stamp){
 store.getProject(projectId);
 if(!SLIDE_STAMP.test(stamp))throw Object.assign(Error('Slide bundle not found.'),{status:404});
 const dir=path.join(store.projectDir(projectId),'slides',stamp);
 const names=(await readdir(dir).catch(()=>[])).filter(n=>/^\d{2}\.png$/.test(n)).sort();
 if(!names.length)throw Object.assign(Error('No slides saved.'),{status:404});
 return zip(await Promise.all(names.map(async name=>({name,data:await readFile(path.join(dir,name))}))));
}
