import path from 'node:path';
import {mkdir,readFile,readdir,writeFile} from 'node:fs/promises';
import {identifyImage,MAX_ASSET_BYTES} from './assets.mjs';
import {panelDrawingRequest,SHOTS} from '../shared/contract.mjs';
const clean=value=>String(value??'').replaceAll('\r','');
const list=value=>(value||[]).map(v=>'- '+clean(v)).join('\n')||'- 아직 없음';
export function toMarkdown(project,profile){const i=project.interpretation;return `# ${clean(project.title)}\n\n${project.sourceMode==='fictional'?'허구의 예시입니다. 실제 경험을 주장하지 않습니다.':'원문에 없는 구체적 공간·소품·행동·대사는 아래의 연출 제안입니다.'}\n\n## 원문 메모\n\n${clean(project.raw)}\n\n## 내가 이해한 이야기\n\n${i?clean(i.summary):'아직 AI 구성을 실행하지 않았습니다.'}\n\n${i?`관점: ${clean(i.angle)}\n\n요점: ${clean(i.keyPoint)}\n\n말투: ${clean(i.tone)}\n\n### 시작 후보\n\n${i.hooks.map((h,n)=>`${n+1}. ${h.text}${n===project.selectedHook?' [선택]':''}\n   ${h.why}\n   첫 장면: ${h.openingScene||''}`).join('\n')}\n\n### 살릴 원문 표현\n\n${list(i.keepPhrases)}\n\n### 원문에서 확인한 내용\n\n${list(i.knownFacts)}\n\n### 해석 또는 가정\n\n${list(i.assumptions)}\n\n### 참고에서 읽은 점\n\n${list(i.referenceNotes)}\n\n### 더 알면 좋은 점\n\n${list(i.questions)}\n\n`:''}## 시리즈 설정\n\n그림체 상태: ${clean(profile.style)}\n\n말투: ${clean(profile.voice)}\n\n맥락: ${clean(profile.context)}\n\n고정 캐릭터: ${clean(profile.characterNotes)||'아직 지정하지 않음'}\n\n피할 것: ${clean(profile.avoid)}\n\n${project.panels.map((p,n)=>`## ${n+1}컷 · ${p.title}\n\n이 컷의 역할: ${p.beat}\n\n시점: ${SHOTS[p.shot]} · ${p.seconds}초\n\n공간: ${p.setting}\n\n행동: ${p.action}\n\n표정·몸짓: ${p.expression}\n\n구도·여백: ${p.composition}\n\n내레이션: ${p.caption||'(없음)'}\n\n대사: ${p.dialogue||'(무대사)'}\n\n근거 구분: ${{source:'원문 기반',interpretation:'맥락 해석',staging:'연출 제안'}[p.sourceKind]||'연출 제안'}\n\n근거와 연출: ${p.sourceNote}\n\n### 그림 요청\n\n${panelDrawingRequest(project,profile,p)}\n\n`).join('')}## 참고 자료\n\n${[...profile.assets,...project.assets].map(a=>`- ${a.role} · ${a.name}${a.characterName?' · '+a.characterName:''}${a.notes?' · '+a.notes:''}`).join('\n')||'없음'}\n`;}
const crcTable=Array.from({length:256},(_,n)=>{for(let k=0;k<8;k++)n=n&1?0xedb88320^(n>>>1):n>>>1;return n>>>0;});
function crc32(b){let c=0xffffffff;for(const v of b)c=crcTable[(c^v)&255]^(c>>>8);return (c^0xffffffff)>>>0;}
export function zip(entries){let offset=0;const parts=[],directory=[];for(const {name,data}of entries){const filename=Buffer.from(name),b=Buffer.isBuffer(data)?data:Buffer.from(data),crc=crc32(b);const h=Buffer.alloc(30);h.writeUInt32LE(0x04034b50);h.writeUInt16LE(20,4);h.writeUInt16LE(0x800,6);h.writeUInt32LE(crc,14);h.writeUInt32LE(b.length,18);h.writeUInt32LE(b.length,22);h.writeUInt16LE(filename.length,26);const d=Buffer.alloc(46);d.writeUInt32LE(0x02014b50);d.writeUInt16LE(20,4);d.writeUInt16LE(20,6);d.writeUInt16LE(0x800,8);d.writeUInt32LE(crc,16);d.writeUInt32LE(b.length,20);d.writeUInt32LE(b.length,24);d.writeUInt16LE(filename.length,28);d.writeUInt32LE(offset,42);parts.push(h,filename,b);directory.push(d,filename);offset+=h.length+filename.length+b.length;}const center=Buffer.concat(directory),end=Buffer.alloc(22);end.writeUInt32LE(0x06054b50);end.writeUInt16LE(entries.length,8);end.writeUInt16LE(entries.length,10);end.writeUInt32LE(center.length,12);end.writeUInt32LE(offset,16);return Buffer.concat([...parts,center,end]);}
export async function exportProject({project,profile,readAsset,format='zip'}){if(!['markdown','json','zip'].includes(format))throw Object.assign(Error('내보내기 형식을 선택해 주세요.'),{status:400});const snapshot={...project,jobs:[],revisions:[]};const data={schemaVersion:2,exportedAt:new Date().toISOString(),project:snapshot,profile,notes:'편집 가능한 원고·그림 요청서 및 이미지 자료입니다. generation 메타데이터가 있는 이미지는 GPT 생성 결과이며, 나머지는 사용자가 가져온 자료입니다.'};if(format==='json')return {data:JSON.stringify(data,null,2),mime:'application/json; charset=utf-8',filename:'comic-story.json'};const markdown=toMarkdown(project,profile);if(format==='markdown')return {data:markdown,mime:'text/markdown; charset=utf-8',filename:'comic-story.md'};const entries=[{name:'story.md',data:markdown},{name:'story.json',data:JSON.stringify(data,null,2)},{name:'series.json',data:JSON.stringify(profile,null,2)}];for(const [n,p]of project.panels.entries())entries.push({name:`drawing-requests/${String(n+1).padStart(2,'0')}.txt`,data:panelDrawingRequest(project,profile,p)});let total=0;const manifest=[];for(const [n,a]of [...profile.assets,...project.assets].entries()){const bytes=await readAsset(a);total+=bytes.length;if(total>200*1024*1024)throw Error('참고 자료가 너무 큽니다. 개별 자료로 나눠 주세요.');const extension={'image/png':'png','image/jpeg':'jpg','image/webp':'webp'}[a.mime]||'bin';const filename=`references/${String(n+1).padStart(2,'0')}-${a.role}.${extension}`;entries.push({name:filename,data:bytes});manifest.push({...a,file:filename,url:undefined});}entries.push({name:'references.json',data:JSON.stringify(manifest,null,2)},{name:'READ-ME.txt',data:'story.md에서 흐름을 검토하고 drawing-requests 폴더의 컷별 요청서를 사용하세요. references.json은 이미지와 역할·캐릭터 이름의 대응표입니다. 현재 시리즈의 그림체 설정과 고정 캐릭터를 기준으로 합니다. 이 패키지는 외부 앱에 자동 게시하지 않습니다.'});return {data:zip(entries),mime:'application/zip',filename:'comic-production.zip'};}
// Instagram slides are rendered in the browser; the server only stores them. Each export gets its own folder so nothing is overwritten.
const SLIDE_STAMP=/^\d{8}-\d{6}$/;
export async function saveSlide(store,projectId,{stamp,index,data}={}){
 store.getProject(projectId);
 if(typeof stamp!=='string'||!SLIDE_STAMP.test(stamp)||!Number.isInteger(index)||index<1||index>10||typeof data!=='string')throw Object.assign(Error('슬라이드 저장 요청이 올바르지 않습니다.'),{status:400});
 const bytes=Buffer.from(data,'base64');
 if(!bytes.length||bytes.length>MAX_ASSET_BYTES||identifyImage(bytes).mime!=='image/png')throw Object.assign(Error('슬라이드는 PNG 이미지여야 합니다.'),{status:400});
 const dir=path.join(store.projectDir(projectId),'slides',stamp),file=path.join(dir,String(index).padStart(2,'0')+'.png');
 await mkdir(dir,{recursive:true});await writeFile(file,bytes);
 return {file,dir};
}
export async function slidesZip(store,projectId,stamp){
 store.getProject(projectId);
 if(!SLIDE_STAMP.test(stamp))throw Object.assign(Error('슬라이드 묶음을 찾을 수 없습니다.'),{status:404});
 const dir=path.join(store.projectDir(projectId),'slides',stamp);
 const names=(await readdir(dir).catch(()=>[])).filter(n=>/^\d{2}\.png$/.test(n)).sort();
 if(!names.length)throw Object.assign(Error('저장된 슬라이드가 없습니다.'),{status:404});
 return zip(await Promise.all(names.map(async name=>({name,data:await readFile(path.join(dir,name))}))));
}
