import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import path from 'node:path';import os from 'node:os';
import {makeProject,makeProfile,makePanel,normalizePlan,panelDrawingRequest} from '../shared/contract.mjs';import {planComic,chooseModel,buildPrompt} from '../engine/planner.mjs';import {exportProject} from '../engine/export.mjs';
const interpretation={summary:'생각은 많은데 말로 정리하기 어렵다는 이야기',angle:'생각과 말 사이',keyPoint:'정리되지 않은 말에도 소재가 있다',tone:'담담한 혼잣말',keepPhrases:['말이 잘 안 나와'],knownFacts:['말이 잘 안 나와'],assumptions:['책상은 연출 제안'],questions:[],referenceNotes:[],hooks:[{text:'말이 없어서가 아니라',why:'반전의 여지',openingScene:'손이 멈춘다.'},{text:'이걸 어디서부터 말하지',why:'구체적인 시작',openingScene:'입을 열었다 닫는다.'},{text:'머릿속은 바쁜데',why:'상황 공감',openingScene:'메모가 책상을 덮는다.'}]};
const panel=n=>makePanel({id:'p'+n,title:n+'컷',beat:'관찰',action:'손에 쥔 메모를 내려놓는다.',composition:'손을 크게 보이고 책상 끝을 대각선으로 둔다.',visualPrompt:'메모를 내려놓는 손의 디테일. 배경은 비우고 글자 없이.',sourceNote:'메모와 책상은 연출 제안.',shot:n===1?'detail':'wide',caption:'',dialogue:''});
function fixture(){const project=makeProject({raw:'음... 말이 잘 안 나와. 그래도 생각은 많아.',profileId:'series_test',interpretation,panels:[panel(1),panel(2)]});return {project,profile:makeProfile({id:'series_test'})};}
test('scene-only revision preserves other panels and invalidates only edited sketch',()=>{const {project}=fixture();project.assets=[{id:'sketch1',role:'sketch'},{id:'sketch2',role:'sketch'}];project.panels[0].sketchAssetId='sketch1';project.panels[1].sketchAssetId='sketch2';const incoming={title:'Should not replace',interpretation,panels:[{...project.panels[0],action:'메모를 다시 집는다.'}]};const result=normalizePlan(incoming,project,{panelId:'p1'});assert.equal(result.panels[0].sketchAssetId,'');assert.deepEqual(result.panels[1],project.panels[1]);assert.equal(result.title,project.title);assert.deepEqual(result.interpretation,project.interpretation);assert.equal(result.panels[0].caption,'');});
test('unquoted factual claims cannot pass as evidence and wrong panel count is rejected',()=>{const {project}=fixture();assert.throws(()=>normalizePlan({title:'제목',interpretation:{...interpretation,knownFacts:['매달 백만 원을 번다']},panels:[panel(1),panel(2)]},project),/원문/);assert.throws(()=>normalizePlan({title:'제목',interpretation,panels:[panel(1),panel(2)]},{...project,panelCount:4}),/컷 수/);});
test('AI correction is bounded and counts both attempts instead of losing usage',async()=>{const {project,profile}=fixture();const dir=await mkdtemp(path.join(os.tmpdir(),'comic-planner-'));let calls=0;try{const result=await planComic({project,profile,request:{model:'auto'},jobDir:dir,referenceImages:[],generate:async()=>({raw:JSON.stringify({title:'말이 없어서가 아니라',interpretation:{...interpretation,knownFacts:++calls===1?['없는 사실']:interpretation.knownFacts},panels:[panel(1),panel(2)]}),usage:{input_tokens:30,output_tokens:15}})});assert.equal(calls,2);assert.equal(result.usage.input_tokens,60);assert.equal(result.usage.output_tokens,30);assert.equal(result.usage.attempts,2);}finally{await rm(dir,{recursive:true,force:true});}});
test('reference roles and character invariants survive drawing request and export',async()=>{const {project,profile}=fixture();profile.characterNotes='모모: 왼쪽 소매에 점 하나';profile.assets=[{id:'ref',role:'character',characterName:'모모',name:'turnaround.png',notes:'정면과 측면',mime:'image/png',bytes:12}];const text=panelDrawingRequest(project,profile,project.panels[0]);assert.match(text,/왼쪽 소매/);assert.match(text,/turnaround.png/);const exp=await exportProject({project,profile,format:'zip',readAsset:async()=>Buffer.from('sample image')});assert.ok(exp.data.includes(Buffer.from('drawing-requests/01.txt')));assert.ok(exp.data.includes(Buffer.from('references/01-character.png')));const prompt=buildPrompt({project,profile,request:{},referenceImages:[{...profile.assets[0],role:'avoid'}]});assert.match(prompt,/"role":"avoid"/);assert.match(prompt,/CURRENT profile\.style/);assert.deepEqual(chooseModel({}),{model:'gpt-6-astra',effort:'high'});assert.deepEqual(chooseModel({panelId:'p1'}),{model:'gpt-5.6-sol',effort:'medium'});});
